-- ==============================================================================
-- discovery_events — uso do modal "Descobrir um Ensinamento"
-- ==============================================================================
-- O recurso existe pra mudar um comportamento (procurar só o necessário →
-- descobrir sem precisar). Sem registro não há como saber se mudou: o clique
-- no botão vira um pageview de leitor igual a qualquer outro, indistinguível
-- de quem chegou pela busca. Foi exatamente esse ponto cego que deixou a busca
-- devolver vazio por três semanas sem ninguém perceber.
--
-- Uma linha por AÇÃO, não por sessão — a pergunta que importa é a conversão:
-- de cada tanto que a pessoa espia, quanto ela abre pra ler de verdade?
--
-- Ações:
--   'open'    — abriu o modal
--   'draw'    — sorteou uma carta (inclui a primeira, automática)
--   'read'    — clicou em "Abrir o Ensinamento"
--   'save'    — guardou pra depois
--   'unsave'  — desfez o guardar
--
-- Retenção: sem trigger automático. Se crescer demais, apagar o que passou de
-- 180 dias — nenhuma análise aqui olha mais longe que isso.
--
-- Execute no SQL Editor do Supabase Dashboard.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.discovery_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action      text NOT NULL CHECK (action IN ('open','draw','read','save','unsave')),
  vol         text,
  file        text,
  topic_index integer,
  only_vol    text,          -- filtro de volume ativo no momento (null = acervo inteiro)
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Consultas do painel são sempre por período (e às vezes por usuário).
CREATE INDEX IF NOT EXISTS idx_discovery_events_created
  ON public.discovery_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_discovery_events_user
  ON public.discovery_events (user_id, created_at DESC);

ALTER TABLE public.discovery_events ENABLE ROW LEVEL SECURITY;

-- O usuário só INSERE o que é dele. Não precisa ler nem apagar: é telemetria,
-- não conteúdo pessoal — e sem SELECT pro dono ninguém consegue varrer a
-- tabela pelo cliente.
DROP POLICY IF EXISTS "Usuarios registram proprios eventos de descoberta" ON public.discovery_events;
CREATE POLICY "Usuarios registram proprios eventos de descoberta"
ON public.discovery_events
FOR INSERT
WITH CHECK ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Admins leem eventos de descoberta" ON public.discovery_events;
CREATE POLICY "Admins leem eventos de descoberta"
ON public.discovery_events
FOR SELECT
USING ( public.is_admin() );

-- ------------------------------------------------------------------
-- admin_discovery_analytics — o painel numa chamada só
-- ------------------------------------------------------------------
-- Agregar no banco em vez de baixar linhas: o cliente do admin já sofre com o
-- cap de 1000 linhas do PostgREST (js/admin/fetch-all.js existe por causa
-- disso), e aqui o volume só cresce.
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_discovery_analytics(days_back int DEFAULT 30)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_since timestamptz := now() - make_interval(days => greatest(1, days_back));
  v_out   jsonb;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'apenas admin';
  END IF;

  SELECT jsonb_build_object(
    'since', v_since,
    'totais', (
      SELECT coalesce(jsonb_object_agg(action, n), '{}'::jsonb)
        FROM (SELECT action, count(*) AS n FROM discovery_events
               WHERE created_at >= v_since GROUP BY action) x
    ),
    'usuarios_distintos', (
      SELECT count(DISTINCT user_id) FROM discovery_events WHERE created_at >= v_since
    ),
    -- Por usuário: quem usa e com que intensidade. Conversão = leituras
    -- abertas / cartas sorteadas.
    'por_usuario', (
      SELECT coalesce(jsonb_agg(u ORDER BY (u->>'sorteios')::int DESC), '[]'::jsonb)
        FROM (
          SELECT jsonb_build_object(
                   'user_id', user_id,
                   'aberturas', count(*) FILTER (WHERE action = 'open'),
                   'sorteios',  count(*) FILTER (WHERE action = 'draw'),
                   'leituras',  count(*) FILTER (WHERE action = 'read'),
                   'guardados', count(*) FILTER (WHERE action = 'save'),
                   'ultimo_uso', max(created_at)
                 ) AS u
            FROM discovery_events
           WHERE created_at >= v_since
           GROUP BY user_id
        ) t
    ),
    -- Dia a dia, pra ver se o hábito pega ou esfria.
    'por_dia', (
      SELECT coalesce(jsonb_agg(d ORDER BY d->>'dia'), '[]'::jsonb)
        FROM (
          SELECT jsonb_build_object(
                   'dia', created_at::date,
                   'aberturas', count(*) FILTER (WHERE action = 'open'),
                   'sorteios',  count(*) FILTER (WHERE action = 'draw'),
                   'leituras',  count(*) FILTER (WHERE action = 'read')
                 ) AS d
            FROM discovery_events
           WHERE created_at >= v_since
           GROUP BY created_at::date
        ) t
    ),
    -- O que a descoberta levou as pessoas a LER (não o que foi sorteado):
    -- é a resposta direta a "está abrindo portas pra fora do de sempre?".
    'mais_lidos', (
      SELECT coalesce(jsonb_agg(m ORDER BY (m->>'n')::int DESC), '[]'::jsonb)
        FROM (
          SELECT jsonb_build_object('vol', vol, 'file', file,
                                    'topic_index', topic_index, 'n', count(*)) AS m
            FROM discovery_events
           WHERE created_at >= v_since AND action = 'read' AND vol IS NOT NULL
           GROUP BY vol, file, topic_index
           ORDER BY count(*) DESC
           LIMIT 20
        ) t
    ),
    -- Distribuição por volume do que foi aberto pra leitura.
    'por_volume', (
      SELECT coalesce(jsonb_object_agg(vol, n), '{}'::jsonb)
        FROM (SELECT vol, count(*) AS n FROM discovery_events
               WHERE created_at >= v_since AND action = 'read' AND vol IS NOT NULL
               GROUP BY vol) x
    )
  ) INTO v_out;

  RETURN v_out;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.admin_discovery_analytics(int) FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.admin_discovery_analytics(int) TO authenticated;
