-- ==============================================================================
-- read_marks — "Ensinamentos Lidos" (marcação manual por tópico, fase 1)
-- Espelha o modelo da synced_favorites: 1 linha por (user, volume, file, topic).
-- Execute no SQL Editor do Supabase Dashboard (ou via psql com SUPABASE_DB_URL).
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.read_marks (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  volume      text NOT NULL,
  file        text NOT NULL,
  topic_index integer NOT NULL DEFAULT 0,
  topic_title text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, volume, file, topic_index)
);

-- Consulta típica: tudo de um usuário (Central) — o índice do UNIQUE já cobre.

ALTER TABLE public.read_marks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios gerenciam proprias marcas de lido" ON public.read_marks;

CREATE POLICY "Usuarios gerenciam proprias marcas de lido"
ON public.read_marks
FOR ALL
USING ( auth.uid() = user_id )
WITH CHECK ( auth.uid() = user_id );

-- Admin pode ler (mesmo padrão de admin_select_favs_highlights, p/ futura
-- visão no painel; inofensivo se is_admin() já existe — e existe).
DROP POLICY IF EXISTS "Admins leem marcas de lido" ON public.read_marks;

CREATE POLICY "Admins leem marcas de lido"
ON public.read_marks
FOR SELECT
USING ( public.is_admin() );
